"""small fix to invoice

Revision ID: 4a4d5526c3b1
Revises: 4eebb0c861bc
Create Date: 2025-07-15 13:38:25.850884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a4d5526c3b1'
down_revision = '4eebb0c861bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('total_amount')

    # ### end Alembic commands ###
